Ejercicios Unión de Datos

In [2]:
import pandas as pd
import numpy as np

Para realizar estos ejercicios deberéis usar el conjunto de datos de world-data-2023-part1.csv y el de world-data-2023-part2.csv.

In [3]:
df_p1 = pd.read_csv('world-data-2023_part1.csv', index_col=0)
df_p1.tail(5)

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175","2,740.27",254.90%,VED,2.27,52.70%,$0.00
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",163.52,2.80%,VND,2.05,48.10%,$0.80
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",157.58,8.10%,YER,3.79,1.00%,$0.92
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.63,65.20%,$1.40
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",105.51,0.90%,NaN,3.62,35.50%,$1.34

In [4]:
df_p2 = pd.read_csv('world-data-2023_part2.csv', index_col=0)
df_p2.tail(5)

,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
190,"$482,359,318,768",97.20%,79.30%,21.4,Caracas,72.1,125.0,$0.01,Spanish,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",Venezuela,"('6.42375 ', '-66.58973')"
191,"$261,921,244,843",110.60%,28.50%,16.5,Ho Chi Minh City,75.3,43.0,$0.73,Vietnamese,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",Vietnam,"('14.058324 ', '108.277199')"
192,"$26,914,402,224",93.60%,10.20%,42.9,Sanaa,66.1,164.0,NaN,Arabic,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",Yemen,"('15.552727 ', '48.516388')"
193,"$23,064,722,446",98.70%,4.10%,40.4,Lusaka,63.5,213.0,$0.24,English,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",Zambia,"('-13.133897 ', '27.849332')"
194,"$21,440,758,800",109.90%,10.00%,33.9,Harare,61.2,458.0,NaN,Shona,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",Zimbabwe,"('-19.015438 ', '29.154857')"

## notas

In [ ]:
df_unido = df_p1.merge(df_p2, how= 'outer', left_on='Country', right_on='country')
df_unido.head(1)

In [7]:
df_unido = df_p1.merge(df_p2, how= 'inner', left_on='Country', right_on='country')
df_unido.head(1)

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"

In [8]:
df_unido = df_p1.merge(df_p2, how= 'left', left_on='Country', right_on='country')
df_unido.head(1)

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"

In [9]:
df_prueba = df_p1.merge(df_p2, how= 'outer', left_on='Country', right_on='country')[['Country', 'country']] #solo de prueba
df_prueba.head(1)

       Country      country
0  Afghanistan  Afghanistan

In [10]:
df_prueba.isna().sum()

Country    0
country    0
dtype: int64

In [11]:
df_unido = df_p1.merge(df_p2, how= 'outer', left_on='Country', right_on='country') #finalmente usamos outer porque queremos mantener la info de ambas tablas
df_unido.head(1)

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"

In [ ]:
df_unido = df_unido.drop(['country'], axis= 1)

In [15]:
df_unido

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')"
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')"
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,Spanish,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368","('6.42375 ', '-66.58973')"
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,Vietnamese,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140","('14.058324 ', '108.277199')"
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,Arabic,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523","('15.552727 ', '48.516388')"
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,English,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713","('-13.133897 ', '27.849332')"
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,Shona,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305","('-19.015438 ', '29.154857')"

In [16]:
df_unido_copia = df_unido.copy()

In [18]:
nuevas_columnas = {columna: columna.lower() for columna in df_unido}

In [19]:
nuevas_columnas

{'Country': 'country',
 'Density\r\n(P/Km2)': 'density\r\n(p/km2)',
 'Abbreviation': 'abbreviation',
 'Agricultural Land( %)': 'agricultural land( %)',
 'Land Area(Km2)': 'land area(km2)',
 'Armed Forces size': 'armed forces size',
 'Birth Rate': 'birth rate',
 'Calling Code': 'calling code',
 'Capital/Major City': 'capital/major city',
 'Co2-Emissions': 'co2-emissions',
 'CPI': 'cpi',
 'CPI Change (%)': 'cpi change (%)',
 'Currency-Code': 'currency-code',
 'Fertility Rate': 'fertility rate',
 'Forested Area (%)': 'forested area (%)',
 'Gasoline Price': 'gasoline price',
 'GDP': 'gdp',
 'Gross primary education enrollment (%)': 'gross primary education enrollment (%)',
 'Gross tertiary education enrollment (%)': 'gross tertiary education enrollment (%)',
 'Infant mortality': 'infant mortality',
 'Largest city': 'largest city',
 'Life expectancy': 'life expectancy',
 'Maternal mortality ratio': 'maternal mortality ratio',
 'Minimum wage': 'minimum wage',
 'Official language': 'official language',
 'Out of pocket health expenditure': 'out of pocket health expenditure',
 'Physicians per thousand': 'physicians per thousand',
 'Population': 'population',
 'Population: Labor force participation (%)': 'population: labor force participation (%)',
 'Tax revenue (%)': 'tax revenue (%)',
 'Total tax rate': 'total tax rate',
 'Unemployment rate': 'unemployment rate',
 'Urban_population': 'urban_population',
 'coordinates': 'coordinates'}

In [20]:
df_unido_copia.rename(columns=nuevas_columnas, inplace=True)
df_unido_copia.head(1)

,country,density\r\n(p/km2),abbreviation,agricultural land( %),land area(km2),armed forces size,birth rate,calling code,capital/major city,co2-emissions,...,official language,out of pocket health expenditure,physicians per thousand,population,population: labor force participation (%),tax revenue (%),total tax rate,unemployment rate,urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"

In [26]:
df_unido_copia.columns

Index(['country', 'density\r\n(p/km2)', 'abbreviation',
       'agricultural land( %)', 'land area(km2)', 'armed forces size',
       'birth rate', 'calling code', 'capital/major city', 'co2-emissions',
       'cpi', 'cpi change (%)', 'currency-code', 'fertility rate',
       'forested area (%)', 'gasoline price', 'gdp',
       'gross primary education enrollment (%)',
       'gross tertiary education enrollment (%)', 'infant mortality',
       'largest city', 'life expectancy', 'maternal mortality ratio',
       'minimum wage', 'official language', 'out of pocket health expenditure',
       'physicians per thousand', 'population',
       'population: labor force participation (%)', 'tax revenue (%)',
       'total tax rate', 'unemployment rate', 'urban_population',
       'coordinates'],
      dtype='object')

In [37]:
columnasnuevas = ['official language', 'country', 'capital/major city', 'abbreviation', 'currency-code']

for c in columnasnuevas:
    df_unido_copia[c]= df_unido_copia[c].str.lower()

print(columnasnuevas)

['official language', 'country', 'capital/major city', 'abbreviation', 'currency-code']

In [38]:
df_unido_copia.head(5)

,country,density\r\n(p/km2),abbreviation,agricultural land( %),land area(km2),armed forces size,birth rate,calling code,capital/major city,co2-emissions,...,official language,out of pocket health expenditure,physicians per thousand,population,population: labor force participation (%),tax revenue (%),total tax rate,unemployment rate,urban_population,coordinates
0,afghanistan,60,af,58.10%,"652,230","323,000",32.49,93.0,kabul,"8,672",...,pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,albania,105,al,43.10%,"28,748","9,000",11.78,355.0,tirana,"4,536",...,albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"
2,algeria,18,dz,17.40%,"2,381,741","317,000",24.28,213.0,algiers,"150,006",...,arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')"
3,andorra,164,ad,40.00%,468,NaN,7.20,376.0,andorra la vella,469,...,catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')"
4,angola,26,ao,47.50%,"1,246,700","117,000",40.73,244.0,luanda,"34,693",...,portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')"

In [40]:
nuevas_columnas = {columna: columna.lower().replace(' ', '_') for columna in df_unido_copia}
df_unido_copia.head()

,country,density\r\n(p/km2),abbreviation,agricultural land( %),land area(km2),armed forces size,birth rate,calling code,capital/major city,co2-emissions,...,official language,out of pocket health expenditure,physicians per thousand,population,population: labor force participation (%),tax revenue (%),total tax rate,unemployment rate,urban_population,coordinates
0,afghanistan,60,af,58.10%,"652,230","323,000",32.49,93.0,kabul,"8,672",...,pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,albania,105,al,43.10%,"28,748","9,000",11.78,355.0,tirana,"4,536",...,albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"
2,algeria,18,dz,17.40%,"2,381,741","317,000",24.28,213.0,algiers,"150,006",...,arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')"
3,andorra,164,ad,40.00%,468,NaN,7.20,376.0,andorra la vella,469,...,catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')"
4,angola,26,ao,47.50%,"1,246,700","117,000",40.73,244.0,luanda,"34,693",...,portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')"

In [41]:
df_unido_copia.rename(columns=nuevas_columnas, inplace=True)
df_unido_copia.head()

,country,density\r\n(p/km2),abbreviation,agricultural_land(_%),land_area(km2),armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,...,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population:_labor_force_participation_(%),tax_revenue_(%),total_tax_rate,unemployment_rate,urban_population,coordinates
0,afghanistan,60,af,58.10%,"652,230","323,000",32.49,93.0,kabul,"8,672",...,pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,albania,105,al,43.10%,"28,748","9,000",11.78,355.0,tirana,"4,536",...,albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"
2,algeria,18,dz,17.40%,"2,381,741","317,000",24.28,213.0,algiers,"150,006",...,arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')"
3,andorra,164,ad,40.00%,468,NaN,7.20,376.0,andorra la vella,469,...,catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')"
4,angola,26,ao,47.50%,"1,246,700","117,000",40.73,244.0,luanda,"34,693",...,portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')"

Hoy tenemos un dataset nuevo, en este encontraremos las siguientes columnas:

GDP: Producto Interno Bruto, el valor total de bienes y servicios producidos en el país.

Gross primary education enrollment (%): Tasa bruta de matriculación en educación primaria.

Gross tertiary education enrollment (%): Tasa bruta de matriculación en educación terciaria.

Infant mortality: Número de muertes por cada 1,000 nacidos vivos antes de cumplir un año de edad.

Largest city: Nombre de la ciudad más grande del país.

Life expectancy: Número promedio de años que se espera que viva un recién nacido.

Maternal mortality ratio: Número de muertes maternas por cada 100,000 nacidos vivos.

Minimum wage: Nivel de salario mínimo en moneda local.

Official language: Idioma(s) oficial(es) hablado(s) en el país.

Out of pocket health expenditure: Porcentaje del gasto total en salud pagado directamente por individuos.

Physicians per thousand: Número de médicos por cada mil personas.

Population: Población total del país.

Population: Labor force participation (%): Porcentaje de la población que forma parte de la fuerza laboral.

Tax revenue (%): Ingresos fiscales como porcentaje del PIB.

Total tax rate: Carga fiscal total como porcentaje de las ganancias comerciales.

Unemployment rate: Porcentaje de la fuerza laboral que está desempleada.

Urban_population: Porcentaje de la población que vive en áreas urbanas.

coordinates: Coordenadas de latitud y longitud de la ubicación del país.

country: Nombre del país.

# Importante

Tienes a tu disposición dos conjuntos de datos, "world-data-2023-part1.csv" y "world-data-2023-part2.csv", que contienen información de una serie de indicadores y datos de distintos países. Tu tarea es explorar estos conjuntos de datos y determinar qué tienen en común en términos de columnas y datos.

Luego, debes crear un nuevo DataFrame que combine la información de ambos conjuntos de datos en un solo conjunto de datos. Para hacerlo, debes seleccionar el método de unión de Pandas que consideres más apropiado para esta situación y justificar por qué crees que ese método es el mejor en tu informe.

Asegúrate de realizar los siguientes pasos:

Explora y carga ambos conjuntos de datos en pandas DataFrames.

Identifica las columnas comunes entre los dos conjuntos de datos.

Utiliza el método de unión de Pandas que consideres más adecuado para combinar los datos de ambos años en un solo DataFrame.

Explica por qué elegiste ese método de unión y cómo se llevaron a cabo los pasos anteriores.

Ejercicios de Limpieza
Después de la unión de datos, tenemos dos columnas de "country". Elimina una de ellas.

Los nombres de las columnas no son homogeneos. Cambia los nombres de las columnas de tal forma que:

No tengan espacios.

Estén en minúscula.

No tengan paréntesis, es decir, quitar "(%)", "(Km2)".

Algunas columnas tiene "\n". Eliminalos de los nombres de las columnas.

Algunas columnas tienen ":". Eliminalos de los nombres de las columnas.

La columnas coordinates tiene la latitud y la longitud en una sola columna. Crea dos columnas nuevas, una con la longitud y otra con la latitud. Una vez hecho, elimina la columna de coordinates.

Las columnas unemployment_rate, total_tax_rate, tax_revenue, population_labor_force_participation, out_of_pocket_health_expenditure, gross_tertiary_education_enrollment, gross_primary_education_enrollment, forested_area, cpi_change, agricultural_land tienen "%". Elimina los "%" de los valores de las columnas.

Haz lo mismo para las columnas de gasoline_price, gdp, minimum_wage, pero eliminando "$".

Guarda el DataFrame para usarlo posteriormente.

Ejercicios de Filtrado
Encuentra todos los países cuya mortalidad infantil esté entre 40 y 50 personas por kilómetro cuadrado.

Encuentra los países cuyas tasas de natalidad son mayores o iguales a 20 y su esperanza de vida es mayor de 75 años.

Encuentra las ciudades cuyos paises contienen la palabra "la" en su nombre.

Encuentra los países cuyos medicos por cada 1000 habitantes (physicians_per_thousand) sea mayores de 5.

Encuentra los países cuyatasa de fertilidad sea mayor a 6.

Encuentra los países cuya moneda es el euro (EUR) y tienen una tasa de natalidad superior al promedio.

Encuentra los países cuyas tasas de mortalidad infantil son superiores a 70.