Es el turno de los DataFrames

Crea un array de dos dimensiones con 4 filas y 3 columnas.

Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

Descarga el archivo "medallas" y carga el DataFrame.

Usando el loc extrae todas las columnas de la fila de Tailandia.

Usando el loc extrae todas las columnas de China e Irán.

Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

Usando el iloc extrae la información de la India. Devolved todas las columnas.

Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

In [3]:
import pandas as pd
import numpy as np

In [4]:
array = np.empty((4,3))

In [5]:
array

array([[9.33678149e-313, 6.79038653e-313, 6.79038653e-313],
       [6.79038653e-313, 6.79038653e-313, 6.79038653e-313],
       [6.79038653e-313, 2.44029516e-312, 2.14321575e-312],
       [2.29175545e-312, 2.16443571e-312, 2.46151512e-312]])

In [10]:
pd.DataFrame(array)

               0              1              2
0  9.336781e-313  6.790387e-313  6.790387e-313
1  6.790387e-313  6.790387e-313  6.790387e-313
2  6.790387e-313  2.440295e-312  2.143216e-312
3  2.291755e-312  2.164436e-312  2.461515e-312

In [11]:
df = pd.DataFrame(array)

In [12]:
df.rename(columns= {0:'España', 1:'Francia', 2: 'Italia'} )

          España        Francia         Italia
0  9.336781e-313  6.790387e-313  6.790387e-313
1  6.790387e-313  6.790387e-313  6.790387e-313
2  6.790387e-313  2.440295e-312  2.143216e-312
3  2.291755e-312  2.164436e-312  2.461515e-312

In [14]:
paises = ['España', 'Francia', 'Italia'] #esta es otra forma de renombrar columnas
df = pd.DataFrame(data=array, columns=paises)
df

          España        Francia         Italia
0  9.336781e-313  6.790387e-313  6.790387e-313
1  6.790387e-313  6.790387e-313  6.790387e-313
2  6.790387e-313  2.440295e-312  2.143216e-312
3  2.291755e-312  2.164436e-312  2.461515e-312

In [19]:
#descargar archivos

dfmedallas = pd.read_csv('C:/Users/maria/Desktop/files/medallas.csv', index_col=0)

In [20]:
dfmedallas

               País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [21]:
dfmedallas.loc[7, :]

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [29]:
dfmedallas.loc[[1, 4], :]

    País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197

In [31]:
dfmedallas.loc[[1, 4], 'Oro' : 'Bronce']

    Oro  Plata  Bronce
1  1473    994     720
4   179    181     197

In [32]:
dfmedallas

               País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [35]:
dfmedallas.iloc[5] #con el iloc accedemos a la posicion, no a la etiqueta

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

In [36]:
dfmedallas.iloc[1::2]

               País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235

In [38]:
dfmedallas.iloc[1::2, 1:4]

     Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235

In [41]:
mask = dfmedallas['Oro'] > 200
mask

1      True
2      True
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
Name: Oro, dtype: bool

In [42]:
dfmedallas.loc[mask]

            País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827

In [45]:
dfmedallas.loc[list(dfmedallas['Oro'] > 200) ]

            País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827

In [46]:
dfmedallas.loc[list(dfmedallas['Oro'] > 200) & (dfmedallas['Plata'] > 1000)  ]

C:\Users\maria\AppData\Local\Temp\ipykernel_32072\1899089995.py:1: FutureWarning: Logical ops (and, or, xor) between Pandas objects and dtype-less sequences (e.g. list, tuple) are deprecated and will raise in a future version. Wrap the object in a Series, Index, or np.array before operating instead.
  dfmedallas.loc[list(dfmedallas['Oro'] > 200) & (dfmedallas['Plata'] > 1000)  ]

    País   Oro  Plata  Bronce
2  Japón  1032   1037     985

In [47]:
dfmedallas.loc[list(dfmedallas['Oro'] > 200) | (dfmedallas['Bronce'] > 700) ]

C:\Users\maria\AppData\Local\Temp\ipykernel_32072\2328147328.py:1: FutureWarning: Logical ops (and, or, xor) between Pandas objects and dtype-less sequences (e.g. list, tuple) are deprecated and will raise in a future version. Wrap the object in a Series, Index, or np.array before operating instead.
  dfmedallas.loc[list(dfmedallas['Oro'] > 200) | (dfmedallas['Bronce'] > 700) ]

            País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827

In [51]:
total = dfmedallas['Oro'] + dfmedallas['Plata'] + dfmedallas['Bronce']
total

1     3187
2     3054
3     2235
4      557
5      537
6      671
7      585
8      483
9      519
10     446
dtype: int64

In [54]:
dfmedallas.insert(4,'total', total)

In [55]:
dfmedallas

               País   Oro  Plata  Bronce  total
1             China  1473    994     720   3187
2             Japón  1032   1037     985   3054
3     Corea del Sur   745    663     827   2235
4              Irán   179    181     197    557
5        Kazajistán   155    158     224    537
6             India   154    202     315    671
7         Tailandia   132    175     278    585
8         Indonesia   112    131     240    483
9      China Taipéi    99    144     276    519
10  Corea del Norte    91    120     235    446

In [56]:
dfmedallas['total'] = dfmedallas['Oro'] + dfmedallas['Plata'] + dfmedallas['Bronce']

In [57]:
dfmedallas

               País   Oro  Plata  Bronce  total
1             China  1473    994     720   3187
2             Japón  1032   1037     985   3054
3     Corea del Sur   745    663     827   2235
4              Irán   179    181     197    557
5        Kazajistán   155    158     224    537
6             India   154    202     315    671
7         Tailandia   132    175     278    585
8         Indonesia   112    131     240    483
9      China Taipéi    99    144     276    519
10  Corea del Norte    91    120     235    446